services:
  rfid-service:
    build:
      dockerfile: Dockerfile
    container_name: rfid-service
    ports:
      - "8083:8083"
    restart: on-failure
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-broker:9092
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka-broker:9092
    networks:
      - asset-spy-network

networks:
  asset-spy-network:
    name: asset-spy-network